#sudo: required
#
#group: edge
#
#services:
# - docker
#
#before_install:
# - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
# - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
# - sudo apt-get update
# - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
#
#install:
# - wget https://s3.amazonaws.com/rebar3/rebar3 && chmod +x rebar3
#
#env:
# - DOCKER_MACHINE_STATUS="Running" DOCKER_MACHINE_IP="0.0.0.0"
#
#language: erlang
#otp_release:
#  - 20.2
#
#before_script:
# - docker version
# - docker info
# - kerl list installations
#
#script:
# - docker pull konnexionsgmbh/db_11_2_xe
# - docker images
# - docker create --shm-size 1G --name oranif_db -p 1521:1521/tcp -e ORACLE_PWD=oracle konnexionsgmbh/db_11_2_xe
# - docker start oranif_db
# - wget -q -P /tmp https://github.com/K2InformaticsGmbH/oranif/wiki/travis/#oracle-instantclient19.3-basic_19.3.0.0.0-2_amd64.deb
# - wget -q -P /tmp https://github.com/K2InformaticsGmbH/oranif/wiki/travis/#oracle-instantclient19.3-sqlplus_19.3.0.0.0-2_amd64.deb
# - sudo apt install /tmp/oracle-instantclient19.3-basic_19.3.0.0.0-2_amd64.deb
# - sudo apt install /tmp/oracle-instantclient19.3-sqlplus_19.3.0.0.0-2_amd64.deb
# - export LD_LIBRARY_PATH=/usr/lib/oracle/19.3/client64/lib/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
# - echo $LD_LIBRARY_PATH
# - ERL_INTERFACE_DIR="$(ls -d ~/otp/$TRAVIS_OTP_RELEASE/lib/erl_interface*/)"
# - OTP_ERTS_DIR="$(ls -d ~/otp/$TRAVIS_OTP_RELEASE/erts*/)"
# - export ERL_INTERFACE_DIR="${ERL_INTERFACE_DIR:0:$((${#ERL_INTERFACE_DIR} - 1))}"
# - export OTP_ERTS_DIR="${OTP_ERTS_DIR:0:$((${#OTP_ERTS_DIR} - 1))}"
# - export LD_LIBRARY_PATH=./priv/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
# - while [ "`docker inspect -f {{.State.Health.Status}} oranif_db`" != "healthy" ]; do docker ps -a; sleep 60; done
# - sleep 60
# - docker ps -a
# #- cd test/
# #- make
# - echo exit | sqlplus sys/oracle@$DOCKER_MACHINE_IP:1521/XE as sysdba @test/travis.sql $(pwd)/log/
# #- cd -
# - rebar3 ct --verbose=true --readable=false --config=test/ct.cfg
#
sudo: required

group: edge

before_install:
  - sudo apt-get update
  - wget https://raw.githubusercontent.com/Vincit/travis-oracledb-xe/master/accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
  - bash ./accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh

env:
  - ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe ORACLE_SID=XE

language: erlang
otp_release:
  - 20.2

install:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3

before_script:
  - kerl list installations

script:
  - ls -alF $ORACLE_HOME
  - export LD_LIBRARY_PATH=$ORACLE_HOME/lib/${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
  - OTP_ERTS_DIR="$(ls -d ~/otp/$TRAVIS_OTP_RELEASE/erts*/)"
  - export OTP_ERTS_DIR="${OTP_ERTS_DIR:0:$((${#OTP_ERTS_DIR} - 1))}"
  - echo exit | sqlplus sys/travis@127.0.0.1:1521/XE as sysdba @test/travis.sql $(pwd)/log/
  - rebar3 ct --verbose=true --readable=false --config=test/ct.cfg --suite=test/jamdb_oracle_SUITE
